blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/wptechnix/di-container/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement for this library
  - name: Bug Report
    url: https://github.com/wptechnix/di-container/issues/new?template=bug_report.md
    about: Report a bug or unexpected behavior
  - name: Questions & Discussions
    url: https://github.com/wptechnix/di-container/discussions
    about: Ask questions and discuss with other community members
  - name: Security Vulnerabilities
    url: https://github.com/wptechnix/di-container/security/policy
    about: Please review our security policy for reporting vulnerabilities
