#!/bin/bash
staged_files=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.php$' || true)

if [ -z "$staged_files" ]; then
  exit 0
fi

echo "Running phpcs on staged files..."
./scripts/composer phpcs -- $staged_files
if [ $? -ne 0 ]; then
  echo "phpcs failed"
  exit 1
fi

echo "Running phpstan on staged files..."
./scripts/composer phpstan -- $staged_files
if [ $? -ne 0 ]; then
  echo "phpstan failed"
  exit 1
fi
